### ISSUE TITLE
Countries not reporting 5/6 digits depth commodity codes

### ISSUE THREAD

**Issue by pachamaltese** [tradestatistics/ts-yearly-datasets#1]
UN Comtrade provides this data:

|Classification |Availability|
|---------------|------------|
|HS rev 1992    |1992 – 2016 |
|HS rev 1996    |1996 – 2016 |
|HS rev 2002    |2002 – 2016 |
|HS rev 2007    |2007 – 2016 |
|SITC rev 1     |1962 – 2016 |
|SITC rev 2     |1976 – 2016 |

For older periods (i.e 1960-1980) SITC was the only classification in use, but some countries reported using 4 digits codes instead of 5 digits codes. This is not a problem itself, but since some countries report less detail then 4 digits will be the feasible finest granularity level.

Here the `summary()` and `group_by()` functions from dplyr are great because SITC (and also HS) codes are nested so you can truncate codes and sum to the upper level. 

This can be understood with an example. Let's look at a part of SITC rev 2:

|code |description                                          |level                                    |
|-----|-----------------------------------------------------|-----------------------------------------|
|0    |Food and live animals chiefly for food               |1                                        |
|00   |Live animals chiefly for food                        |2                                        |
|001  |Live animals chiefly for food                        |3                                        |
|0011 |Animals of the bovine species (including buffaloes), live                                    |4   |
|00111|Animals of the bovine species (including buffaloes),live; pure bred for breeding            |5   |
|00119|Animals of the bovine species (including buffaloes), live; other than pure bred for breeding|5   |
|...  |                                                     |                                         |

For example, if the USA reports many rows containing both 00111 and 00119 to different countries but BRA reports just 0011, like this:

 |reporter_iso|partner_iso|commodity_code|trade_value_usd|
|------------|------------|---------------|----------------|
|usa         |can         |00111          |100             |
|usa         |can         |00119          |200             |
|usa         |mex         |00111          |300             |
|usa         |mex         |00119          |400             |
|bra         |arg         |0011           |500             |
|usa         |chl         |0011           |600             |

The solution here (for uniformity), and assuming my table is called `data` is to do:

```
library(tidyverse)

data <- read_csv("reporter_iso, partner_iso, commodity_code, trade_value_usd
  usa, can, 00111, 100
  usa, can, 00119, 200
  usa, mex, 00111, 300
  usa, mex, 00119, 400
  bra, arg, 0011, 500
  usa, chl, 0011, 600"
)

data %>% 
  mutate(commodity_code = str_sub(commodity_code, 1, 4)) %>% 
  group_by(reporter_iso, partner_iso, commodity_code) %>% 
  summarise(trade_value_usd = sum(trade_value_usd))

# A tibble: 4 x 4
# Groups:   reporter_iso, partner_iso [?]
  reporter_iso partner_iso commodity_code trade_value_usd
  <chr>        <chr>       <chr>                    <int>
1 bra          arg         0011                       500
2 usa          can         0011                       300
3 usa          chl         0011                       600
4 usa          mex         0011                       700
```

**Comment by pachamaltese** [comment]
Hi @aedobbyn @cimentadaj @jbkunst 

Now we have HS07 data for the period 1962-2016 (HS07 originally exists since 2007) :D

What I did was:

1. Use str_sub to get a "smaller" product_correpondence (UN official table) with 4 digits instead of 6
2. For each dataset (i.e. hs-rev1992-2000-csv, this is hs92 codes for year 2000 trade data) I did a left_join with the product_correpondence
3. In case a code matched multiple entries (i.e 0001 in HS92 matches both 0002 and 0003 in HS07) the first match remains and the rest is discarded

Then I wrote a long code that can be abridged to this pseudo code:

```r
if (year %in% "years where HS92 data exists") {
 data <- fread("hs92-year >= 1992.csv")
 data2 <- fread("sitc2 data of the same year") %>% anti_join(data)
 data3 <- fread("sitc1 data of the same year") %>% anti_join(data) %>% anti_join(data2)

 data <- bind_rows(data, data2, data3)
 # because both existed before HS92 and some regions are slow to adopt new codes, and in oldness sitc1 > sitc2 > hs92
}
... etc ...
```

Do you like this approach? if you like it, then I can go and create other tables with metrics and percentages for the API.

I sent an email with the commands to download the data.

**Comment by pachamaltese** [comment]
Hi @aedobbyn, @jbkunst and @cimentadaj 
I wrote a long long issue above that explains exactly what I did to convert and complete data.
Probably you have better ideas :)
Have a good weekend !!

**Comment by cimentadaj** [comment]
Hi @pachamaltese, very sorry for the long silence. I had a look at the first problem and I understand it perfectly. One concern though: Would this harmonization between countries eventually lead to have only the highest categories in most cases? I mean if there's at least one country which doesn't have 4 digits, then any comparison against this one will inevitably force this country to be recoded to the least digits.

I understand the problem but I think this is a minimal problem looking at the big picture. If a user chooses two countries (which I think is the maximum to compare?) then we just round up to the least digits available between two countries.

Will read the second and third and let you know soon.

**Comment by pachamaltese** [comment]
Thanks a lot Jorge !!
You're right. My solution is quite extreme and it works, but now that you
mention it, it is perfectly feasible to use `nchar(commodity_code)` and
avoid double countings (i.e. exports of Spain = sum of hs4 + hs6, which is
wrong, as it would sum "jars of milk, all of them" plus "jars of milk,
plastic bottle" plus "jars of milk, glass bottle")

**Comment by pachamaltese** [comment]
@cimentadaj finally I've got some time to think and code
I just edited some scripts to include your thoughts about 4 vs 5/6 length codes :)
Probably this weekend I can upload some files to the server, thanks for the critical comments, that always helps !!

**Comment by pachamaltese** [comment]
@cimentadaj Hi

Today I had some time to think about this and code.
I was able to fill all the gaps (i.e countries still missing from HS datasets in 2018 because they report using SITC) while preserving all the information possible.

My solution was to divide the problem in smaller chunks and benefit from codes "nestedness". So, to have access to the full HS07 series for 1962-2016 you can run this:
rsync -av --update jorge@data.local:/public_www/data/04-unified-data/hs-rev2007 04-unified-data/hs-rev2007

Now I'll be creating some tables from that and then to PSQL.
